module.exports = {
  projects: [
    '<rootDir>/apps/client/app',
    '<rootDir>/apps/server/api',
    '<rootDir>/libs/core',
    '<rootDir>/libs/ui/overlog',
    '<rootDir>/libs/ui/controls',
    '<rootDir>/libs/ui/carousel',
    '<rootDir>/libs/sample/restart-ice',
    '<rootDir>/libs/sample/peer-to-peer',
    '<rootDir>/libs/sample/perfect-negotiation',
    '<rootDir>/libs/shared',
    '<rootDir>/libs/ui/meeting',
    '<rootDir>/libs/user/signup',
    '<rootDir>/libs/user/profile',
    '<rootDir>/libs/util/auth',
    '<rootDir>/libs/user/domain',
    '<rootDir>/libs/data/access',
  ],
}
